### ISSUE TITLE
Error C1083 Cannot open include file: 'MinHook.h'

### ISSUE THREAD

**Issue by johnjohnsp1** [rweijnen/createdump#2]
Hi,
thanks for sharing the code, actually im trying to compile it using windows 10 pro and VStudio2023.
once i load the project and do a release compile getting this error as result

Severity
Code
Description
Project
File
Line
Suppression State
Details
Error
C1083
Cannot open include file: 'MinHook.h': No such file or directory
dbgcore
C:\temp\createdump\dbgcore\dllmain.cpp
line 4

i have installed vcpkg and made already vcpkg install minhook

im missing anything or do anything wrong ?

thanks

**Comment by rweijnen** [comment]
I used:
```
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
.\vcpkg install minhook:x64-windows-static
```

In the project properties set:

![vcdirectories](https://github.com/user-attachments/assets/d879ec97-a94f-4b88-8cef-031690f8a8ad)

![linker-general](https://github.com/user-attachments/assets/182d059b-1728-497b-bb36-c4e2cab872dd)

![linker-input](https://github.com/user-attachments/assets/c2aca5fe-3fab-42ce-8eac-c72294fdb6e6)

**Comment by johnjohnsp1** [comment]
thanks for the hint, I can compile it correctly:

Build started at 12:11 PM...
1>------ Build started: Project: dbgcore, Configuration: Release x64 ------
1>pch.cpp
1>dllmain.cpp
1>   Creating library C:\temp\createdump\x64\Release\dbgcore.lib and object C:\temp\createdump\x64\Release\dbgcore.exp
1>Generating code
1>0 of 13 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
1>  0 functions were new in current compilation
1>  0 functions had inline decision re-evaluated but remain unchanged
1>Finished generating code
1>dbgcore.vcxproj -> C:\temp\createdump\x64\Release\dbgcore.dll
1>'pwsh.exe' is not recognized as an internal or external command,
1>operable program or batch file.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:11 PM and took 06.720 seconds ==========

thought an exe file will be created instead a dll suppose that the right idea since if I switch to application "exe" will give me this error:

<img width="932" alt="Screenshot 2024-09-30 alle 12 13 49" src="https://github.com/user-attachments/assets/215bd711-eceb-4f14-99e2-183680687c0e">
<img width="804" alt="Screenshot 2024-09-30 alle 12 13 32" src="https://github.com/user-attachments/assets/3dfb3553-46d3-4971-a707-7ffd4fd3f62c">
